=== AmbientXYZ/CarbonMod/World.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!-- definition of simple types-->
  <xs:simpleType name="blockMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Simple" />
      <xs:enumeration value="ChamferedCorners" />
      <xs:enumeration value="ChamferedEdges" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="state">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Solid" />
      <xs:enumeration value="Liquid" />
      <xs:enumeration value="Gas" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="entityType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Standard" />
      <xs:enumeration value="Cache" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ownerChunkCount">
    <xs:restriction base="xs:int">
      <xs:enumeration value="64" />
      <xs:enumeration value="256" />
      <xs:enumeration value="1024" />
      <xs:enumeration value="4096" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="playerChunkCount">
    <xs:restriction base="xs:int">
      <xs:enumeration value="1" />
      <xs:enumeration value="4" />
      <xs:enumeration value="16" />
      <xs:enumeration value="64" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="latitude">
    <xs:restriction base="xs:int">
      <xs:enumeration value="0" />
      <xs:enumeration value="1024" />
      <xs:enumeration value="2048" />
      <xs:enumeration value="3072" />
      <xs:enumeration value="4096" />
      <xs:enumeration value="5120" />
      <xs:enumeration value="6144" />
      <xs:enumeration value="7168" />
      <xs:enumeration value="8192" />
      <xs:enumeration value="9216" />
      <xs:enumeration value="10240" />
      <xs:enumeration value="11264" />
      <xs:enumeration value="12288" />
      <xs:enumeration value="13312" />
      <xs:enumeration value="14336" />
      <xs:enumeration value="15360" />
      <xs:enumeration value="16384" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="seed">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="livingGrowthYears">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="7" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="livingTrunkThickness">
    <xs:restriction base="xs:int">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="2" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="id">
    <xs:restriction base="xs:byte">
      <xs:enumeration value="0" />
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
      <xs:enumeration value="3" />
      <xs:enumeration value="4" />
      <xs:enumeration value="5" />
      <xs:enumeration value="6" />
      <xs:enumeration value="7" />
      <xs:enumeration value="8" />
      <xs:enumeration value="9" />
      <xs:enumeration value="10" />
      <xs:enumeration value="11" />
      <xs:enumeration value="12" />
      <xs:enumeration value="13" />
      <xs:enumeration value="14" />
      <xs:enumeration value="15" />
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="idShort">
    <xs:restriction base="xs:byte">
      <xs:enumeration value="0" />
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
      <xs:enumeration value="3" />
      <xs:enumeration value="4" />
      <xs:enumeration value="5" />
      <xs:enumeration value="6" />
      <xs:enumeration value="7" />
      <xs:enumeration value="8" />
      <xs:enumeration value="9" />
      <xs:enumeration value="10" />
      <xs:enumeration value="11" />
      <xs:enumeration value="12" />
      <xs:enumeration value="13" />
      <xs:enumeration value="14" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="nibble">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Min" />
      <xs:enumeration value="0" />
      <xs:enumeration value="1" />
      <xs:enumeration value="2" />
      <xs:enumeration value="3" />
      <xs:enumeration value="4" />
      <xs:enumeration value="5" />
      <xs:enumeration value="6" />
      <xs:enumeration value="7" />
      <xs:enumeration value="8" />
      <xs:enumeration value="9" />
      <xs:enumeration value="10" />
      <xs:enumeration value="11" />
      <xs:enumeration value="12" />
      <xs:enumeration value="13" />
      <xs:enumeration value="14" />
      <xs:enumeration value="15" />
      <xs:enumeration value="Max" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="extrudeheight">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value ="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="generationMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Radical" />
      <xs:enumeration value="Extreme2" />
      <xs:enumeration value="Extreme" />
      <xs:enumeration value="Rugged" />
      <xs:enumeration value="Rolling" />
      <xs:enumeration value="Flat" />
      <xs:enumeration value="ShangriLa" />
      <xs:enumeration value="BlankCanvas" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="lifeMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="None" />
      <xs:enumeration value="Living" />
      <xs:enumeration value="Terraform" />
      <xs:enumeration value="Genesis" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="material">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Aggregate" />
      <xs:enumeration value="Carbon" />
      <xs:enumeration value="Stone" />
      <xs:enumeration value="Metal" />
      <xs:enumeration value="Steel" />
      <xs:enumeration value="SteelReinforcedConcrete" />
      <xs:enumeration value="Plant" />
      <xs:enumeration value="Wood" />
      <xs:enumeration value="Other" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="generation">
    <xs:restriction base="xs:string">
      <xs:enumeration value="VeryCommon" />
      <xs:enumeration value="Common" />
      <xs:enumeration value="UnCommon" />
      <xs:enumeration value="Rare" />
      <xs:enumeration value="VeryRare" />
      <xs:enumeration value="Living" />
      <xs:enumeration value="NotApplicable" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="livingGeneration">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Leaves" />
      <xs:enumeration value="GroundCover" />
      <xs:enumeration value="Shrub" />
      <xs:enumeration value="Tree" />
      <xs:enumeration value="PlantSpring" />
      <xs:enumeration value="PlantSummer" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="livingShape">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Pyramidal" />
      <xs:enumeration value="Round" />
      <xs:enumeration value="Columnar" />
      <xs:enumeration value="Weeping" />
      <xs:enumeration value="Vase" />
      <xs:enumeration value="Umbrella" />
      <xs:enumeration value="Palm" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="style">
    <xs:restriction base="xs:string">
      <!--try to get rid of air!!!!-->
      <xs:enumeration value="Air" /> 
      <xs:enumeration value="Standard" />
      <xs:enumeration value="Isolated" />
      <xs:enumeration value="Stair" />
      <xs:enumeration value="Half" />
      <xs:enumeration value="Translucent" />
      <xs:enumeration value="Extrude" />
      <xs:enumeration value="Null" />
      <xs:enumeration value="Custom" />
      <xs:enumeration value="Door" />
      <xs:enumeration value="Window" />
      <!--<xs:enumeration value="Living" />-->
      <!--<xs:enumeration value="Custom" />-->
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="textureGenerationMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Never" />
      <xs:enumeration value="Always" />
      <xs:enumeration value="IfMissing" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="rgbColor">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9A-Fa-f]{2}[0-9A-Fa-f]{2}([0-9A-Fa-f]{2})?" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="gameModeEnum">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Play" />
      <xs:enumeration value="Explore" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="achievement">
    <xs:attribute name="Id" type="xs:unsignedByte" use="required" />
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="Description" type="xs:string" use="optional" default="" />
    <xs:attribute name="Texture" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="texture">
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="GenerationMode" type="textureGenerationMode" use="optional" default="Never" />
    <xs:attribute name="GenerationRGBColor" type="rgbColor" use="optional" default="FFFFFF" />
    <xs:attribute name="Base" type="xs:string" use="optional" default="" />
  </xs:complexType>

  <xs:complexType name="tool">
    <xs:attribute name="Id" type="id" use="required" />
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="Description" type="xs:string" use="optional" default="" />
    <xs:attribute name="Texture" type="xs:string" use="required" />
    <xs:attribute name="Materials" type="xs:string" use="required" />
  </xs:complexType>

  <xs:complexType name="formula">
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="Description" type="xs:string" use="optional" default="" />
    <xs:attribute name="Machine" type="xs:string" use="required" />
    <xs:attribute name="ProductionAmount" type="xs:int" use="required" />
    <xs:attribute name="Source" type="xs:string" use="required" />
    <xs:attribute name="SourceAmount" type="xs:string" use="required" />
    <xs:attribute name="Fuel" type="xs:string" use="required" />
  </xs:complexType>

  <!-- definition of complex types-->
  <xs:complexType name="block">
    <xs:attribute name="Id" type="id" use="required" />
    <xs:attribute name="Name" type="xs:string" use="required" />
    <xs:attribute name="Description" type="xs:string" use="optional" default="" />
    <xs:attribute name="Generation" type="generation" use="required" />
    <xs:attribute name="ExtrudeHeight" type="extrudeheight" default="1.0" />
    <xs:attribute name="Style" type="style" default="Standard" />
    <!--<xs:attribute name="Density" type="nibble" default="7" />-->
    <xs:attribute name="Opacity"  type="nibble" use="optional" default="Max" />
    <xs:attribute name="Luminance" type="nibble" use="optional" default="Min" />
    <xs:attribute name="Radiance" type="nibble" use="optional" default="Min" />
    <xs:attribute name="State" type="state" use="optional" default="Solid" />
    <xs:attribute name="SaturationGenerate" type="nibble" use="optional" default="Max" />
    <xs:attribute name="SaturationApply" type="nibble" use="optional" default="14" />
    <xs:attribute name="Enabled" type="xs:boolean" use="optional" default="true" />
    <xs:attribute name="SaleMultiplier" type="xs:int" use="optional" default="2" />
    <xs:attribute name="Material" type="material" use="optional" default="Stone" />
    <xs:attribute name="Texture" type="xs:string" use="required" />
    <xs:attribute name="TextureTop" type="xs:string" use="optional" default="" />
    <xs:attribute name="TextureBottom" type="xs:string" use="optional" default="" />
    <xs:attribute name="TextureNorth" type="xs:string" use="optional" default="" />
    <xs:attribute name="TextureSouth" type="xs:string" use="optional" default="" />
    <xs:attribute name="TextureWest" type="xs:string" use="optional" default="" />
    <xs:attribute name="TextureEast" type="xs:string" use="optional" default="" />
    <xs:attribute name="LivingGeneration" type="livingGeneration" use="optional" default="GroundCover" />
    <xs:attribute name="LivingDormancyTemperature" type="xs:int" use="optional" default="-30" />
    <xs:attribute name="LivingGrowthTemperature" type="xs:int" use="optional" default="30" />
    <xs:attribute name="LivingWaterNeed" type="xs:int" use="optional" default="10" />
    <xs:attribute name="LivingGrowthYears" type="livingGrowthYears" use="optional" default="1" />
    <xs:attribute name="LivingSpread" type="xs:int" use="optional" default="3" />
    <xs:attribute name="LivingTrunkThickness" type="livingTrunkThickness" use="optional" default="1" />
    <xs:attribute name="LivingShape" type="livingShape" use="optional" default ="Round" />
    <xs:attribute name="LivingLeavesBlock" type="xs:string" use="optional" default ="Leaves" />
    <xs:attribute name="Formula" type="xs:string" use="optional" default ="" />
    <xs:attribute name="EntityType" type="entityType" use="optional" default ="Standard" />
    <xs:attribute name="Flow" type="xs:boolean" use="optional" default ="false" />
  </xs:complexType>

  <xs:element name="World">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Textures" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Generated" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Texture" type="texture" minOccurs="0" maxOccurs="256">
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="System" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Texture" type="texture" minOccurs="0" maxOccurs="8">
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="SeasonalGroundCover" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Texture" type="texture" minOccurs="0" maxOccurs="4">
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="SeasonalLeaves" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Texture" type="texture" minOccurs="0" maxOccurs="4">
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="Achievements" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Achievement" type="achievement" minOccurs="0" maxOccurs="256">
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="AcheivementUniqueId">
            <xs:selector xpath="Achievement" />
            <xs:field xpath="@Id" />
          </xs:unique>
        </xs:element>


        <xs:element name="Tools" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Tool" type="tool" minOccurs="0" maxOccurs="16">
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="ToolUniqueId">
            <xs:selector xpath="Tool" />
            <xs:field xpath="@Id" />
          </xs:unique>
        </xs:element>

        <xs:element name="Formulas" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Formula" type="formula" minOccurs="0" maxOccurs="256">
              </xs:element>
            </xs:sequence>
          </xs:complexType>
          <xs:unique name="FormulaUniqueId">
            <xs:selector xpath="Formula" />
            <xs:field xpath="@Name" />
          </xs:unique>
        </xs:element>

        <xs:element name="Generation" minOccurs="1" maxOccurs="1">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="BlockClass" minOccurs="3" maxOccurs="15">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Block" type="block" minOccurs="0" maxOccurs="16">
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="Name" type="xs:string" use="required" />
                  <xs:attribute name="Id" type="idShort" use="required" />
                </xs:complexType>
                <xs:unique name="BlockUniqueId">
                  <xs:selector xpath="Block" />
                  <xs:field xpath="@Id" />
                </xs:unique>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string" use="optional" default="XML World" />
            <xs:attribute name="GameMode" type="gameModeEnum" use="optional" default="Play" />
            <xs:attribute name="GenerationMode" type="generationMode" use="optional" default="Rugged" />
            <xs:attribute name="LifeMode" type="lifeMode" use="optional" default="Living" />
            <xs:attribute name="GenerationSeed" type="seed" use="optional" default=".4739283232" />
            <xs:attribute name="HomeLatitude" type="latitude" use="optional" default="11264" />
            <xs:attribute name="BlockMode" type="blockMode" use="optional" default="ChamferedEdges" />
            <xs:attribute name="StartDate" type="xs:date" use="optional" default="0001-04-15" />
            <xs:attribute name="Plugin" type="xs:string" use="optional" default="CarbonMod.dll" />
            <xs:attribute name="OwnerChunkCount" type="ownerChunkCount" use="optional" default="256" />
            <xs:attribute name="PlayerChunkCount" type="playerChunkCount" use="optional" default="1" />
          </xs:complexType>
          <xs:unique name="BlockClassUniqueId">
            <xs:selector xpath="BlockClass" />
            <xs:field xpath="@Id" />
          </xs:unique>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AmbientXYZ/CarbonMod/World.xml
<?xml version='1.0' encoding='utf-8'?>

<World
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="World.xsd">

  <Textures>
    <Generated>
      <Texture Name="Palm.png" GenerationRGBColor="AB9283" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Ceiba.png" GenerationRGBColor="78735F" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="SouthernMagnolia.png" GenerationRGBColor="898884" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Cypress.png" GenerationRGBColor="949492" GenerationMode="Always" Base="BaseTreeHardwood.png" />
      <Texture Name="Mahogany.png" GenerationRGBColor="746265" GenerationMode="Always" Base="BaseTreeHardwood.png" />
      <Texture Name="Toog.png" GenerationRGBColor="AA8B6A" GenerationMode="Always" Base="BaseTreeHardwood.png" />
      <Texture Name="Beech.png" GenerationRGBColor="686152" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Acacia.png" GenerationRGBColor="6D5336" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Breadfruit.png" GenerationRGBColor="BCBBB7" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Lychee.png" GenerationRGBColor="A99385" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="CarmelAlmond.png" GenerationRGBColor="9B9195" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Pencil.png" GenerationRGBColor="A2868B" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Malabar.png" GenerationRGBColor="7C6720" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Poplar.png" GenerationRGBColor="D9BD9D" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Ash.png" GenerationRGBColor="B7969A" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="BrazilNut.png" GenerationRGBColor="766943" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Fig.png" GenerationRGBColor="937B59" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="YellowWalnut.png" GenerationRGBColor="8F7146" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Jambul.png" GenerationRGBColor="906A40" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="BlackWalnut.png" GenerationRGBColor="875D34" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Koompassia.png" GenerationRGBColor="A88F72" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Eucalyptus.png" GenerationRGBColor="9D7841" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Tualang.png" GenerationRGBColor="B3ACA4" GenerationMode="Always" Base="BaseTreeHardwood.png" />
      <Texture Name="Durian.png" GenerationRGBColor="6D5444" GenerationMode="Always" Base="BaseTreeHardwood.png" />
      <Texture Name="JackFruit.png" GenerationRGBColor="B9A59A" GenerationMode="Always" Base="BaseTreeHardwood.png" />
      <Texture Name="Maple.png" GenerationRGBColor="7F7A77" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Oak.png" GenerationRGBColor="AC9384" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="PlaneTree.png" GenerationRGBColor="A68473" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Elm.png" GenerationRGBColor="939091" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Redwood.png" GenerationRGBColor="A8756B" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="DouglasFir.png" GenerationRGBColor="A8978F" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Fir.png" GenerationRGBColor="99826A" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="PonderosaPine.png" GenerationRGBColor="8E533F" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Birch.png" GenerationRGBColor="EEEFF4" GenerationMode="Always" Base="BaseTreeHardwood.png" />
      <Texture Name="Alder.png" GenerationRGBColor="9A918C" GenerationMode="Always" Base="BaseTreeHardwood.png" />
      <Texture Name="Pine.png" GenerationRGBColor="6D5551" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="WoodBeam.png" GenerationRGBColor="E8CBA2" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="SteelBeam.png" GenerationRGBColor="6E6E6E" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="BlueSpruce.png" GenerationRGBColor="969797" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Spruce.png" GenerationRGBColor="6C6466" GenerationMode="Always" Base="BaseTree.png" />
      <Texture Name="Grass0.png" GenerationRGBColor="545E1E" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Grass1.png" GenerationRGBColor="555E1E" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Grass2.png" GenerationRGBColor="565E1E" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Grass3.png" GenerationRGBColor="575E1E" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="LeavesBroad0.png" GenerationRGBColor="2B4200" GenerationMode="Always" Base="BaseLeavesBroad0.png" />
      <Texture Name="LeavesBroad1.png" GenerationRGBColor="426300" GenerationMode="Always" Base="BaseLeavesBroad1.png" />
      <Texture Name="LeavesBroad2.png" GenerationRGBColor="5A8764" GenerationMode="Always" Base="BaseLeavesBroad2.png" />
      <Texture Name="LeavesBroad3.png" GenerationRGBColor="788335" GenerationMode="Always" Base="BaseLeavesBroad3.png" />
      <Texture Name="LeavesNeedle0.png" GenerationRGBColor="44621A" GenerationMode="Always" Base="BaseLeavesNeedle0.png" />
      <Texture Name="LeavesNeedle1.png" GenerationRGBColor="818C13" GenerationMode="Always" Base="BaseLeavesNeedle1.png" />
      <Texture Name="LeavesNeedle2.png" GenerationRGBColor="73AA7E" GenerationMode="Always" Base="BaseLeavesNeedle2.png" />
      <Texture Name="LeavesBlueSpruce.png" GenerationRGBColor="6A899D" GenerationMode="Always" Base="BaseLeavesNeedle2.png" />
      <Texture Name="LeavesPalm.png" GenerationRGBColor="4B4E0E" GenerationMode="Always" Base="BaseLeavesPalm0.png" />
      <Texture Name="Saguaro.png" GenerationRGBColor="7C8E75" GenerationMode="Always" Base="BaseNoiseMediumContrast.png" />
      <Texture Name="GoldenBarrel.png" GenerationRGBColor="9CA26C" GenerationMode="Always" Base="BaseNoiseHighContrast.png" />
      <Texture Name="EnglishYew.png" GenerationRGBColor="516332" GenerationMode="Always" Base="BaseLeavesNeedle0.png" />
      <Texture Name="Cordia.png" GenerationRGBColor="79844E" GenerationMode="Always" Base="BaseLeavesNeedle0.png" />
      <Texture Name="Jojoba.png" GenerationRGBColor="979D52" GenerationMode="Always" Base="BaseLeavesNeedle0.png" />
      <Texture Name="CandleBush.png" GenerationRGBColor="606D59" GenerationMode="Always" Base="BaseLeavesBroad0.png" />
      <Texture Name="GoldenDewdrop.png" GenerationRGBColor="548343" GenerationMode="Always" Base="BaseLeavesNeedle1.png" />
      <Texture Name="Ixora.png" GenerationRGBColor="798A3D" GenerationMode="Always" Base="BaseLeavesNeedle2.png" />
      <Texture Name="Reserved.png" GenerationRGBColor="0A0A0A" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="RockTBD.png" GenerationRGBColor="A0A0A0" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="OreTBD.png" GenerationRGBColor="A0A0A0" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="GemTBD.png" GenerationRGBColor="A0A0A0" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Bedrock.png" GenerationRGBColor="0A0A0A" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Soil.png" GenerationRGBColor="8F6B5A" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Sand.png" GenerationRGBColor="DBB87E" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Gravel.png" GenerationRGBColor="A6988E" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="CoarseGravel.png" GenerationRGBColor="A38772" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Granite.png" GenerationRGBColor="A9AAAB" GenerationMode="Always" Base="BaseNoiseHighContrast.png" />
      <Texture Name="Basalt.png" GenerationRGBColor="8D8183" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Clay.png" GenerationRGBColor="BBAE9D" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Sandstone.png" GenerationRGBColor="C6A876" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Marble.png" GenerationRGBColor="DDBE9D" GenerationMode="Always" Base="BaseVeined.png" />
      <Texture Name="Coal.png" GenerationRGBColor="48484D" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Charcoal.png" GenerationRGBColor="58585D" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Limestone.png" GenerationRGBColor="C8B893" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Slate.png" GenerationRGBColor="535C6B" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Flint.png" GenerationRGBColor="88725B" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="Phosphorus.png" GenerationRGBColor="50F991" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="AluminumOre.png" GenerationRGBColor="DF755A" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="IronOre.png" GenerationRGBColor="B96030" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="CopperOre.png" GenerationRGBColor="62D0C9" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="SilverOre.png" GenerationRGBColor="839195" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="GoldOre.png" GenerationRGBColor="C7AD47" GenerationMode="Always" Base="BaseNoise.png" />
      <Texture Name="ChromiumOre.png" GenerationRGBColor="A3A7AA" GenerationMode="Always" Base="BaseNoise.png" />
